FROM node as build
WORKDIR /app
COPY package.json ./
RUN yarn
COPY . .
ARG REACT_APP_VARIABLE
ENV REACT_APP_VARIABLE=$REACT_APP_VARIABLE
RUN yarn run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
